### ISSUE TITLE
The script to install ior, fio, smallfile looks broken for RHEL 7.6 ami (ami-011b3ccf1bd6db744)

### ISSUE THREAD

**Issue by nassy20** [aws-samples/amazon-fsx-workshop#2]
Errors that I got after running script-

#python ~/smallfile/smallfile_cli.py
ERROR: you must ensure that shared directory /var/tmp/smf is accessible from this host and every remote host in test

#ior
bash: ior: command not found

fio also failed to install but I fixed it using --skip-broken

**Comment by darrylsosborne** [comment]
Updated entire workshop to use Amazon Linux 2 and install smallfile manually.
