### ISSUE TITLE
Lustre on 18.04 LTS from aws

### ISSUE THREAD

**Issue by pythonmobile** [aws-samples/amazon-fsx-workshop#3]
Can we get a lustre client for 18.04LTS. At this point lustre only works on 16.04 on aws - which is EOL.

**Comment by darrylsosborne** [comment]
FSx for Lustre now supports Lustre clients on 18.04 and 20.04 - https://docs.aws.amazon.com/fsx/latest/LustreGuide/install-lustre-client.html
